### ISSUE TITLE
🗑️ 🦝  [Spring Cleaning] Rename packages and update documentation 

### ISSUE THREAD

**Issue by sserrata** [PaloAltoNetworks/docusaurus-openapi#63]
## Description

This issue is for tracking progression through renaming repository and packages and updating all supporting licenses and docs, e.g. READMEs, license headers, usage, screenshots, etc.

Proposed naming:

Repository: `docusaurus-openapi-docs`
Plugin: `docusaurus-plugin-openapi-docs`
Theme: `docusaurus-theme-openapi-docs`

Logo: TBD

## Motivation

Since forking the original [docusaurus-openapi](https://github.com/cloud-annotations/docusaurus-openapi) we have diverged enough to warrant breaking the fork and spinning off our own project. With that said, we'd like to remain friendly to the rest of the Docusaurus community by packaging and offering our version of the plugin such that other Docusaurus users may potentially use it in their projects.

## TODO
- [ ] Update `README.md` (screenshots and usage)
- [ ] Update `LICENSE` (and `.eslintrc.js` rules) (adopt panw license)
- [ ] Update `CONTRIBUTING.md`
- [ ] Add `SUPPORT.md` (adopt panw community support)
- [ ] Update `CODE_OF_CONDUCT.md` (adopt panw if appropriate)
- [ ] Update `docusaurus-plugin-openapi` `README.md` (screenshots and usage)
- [ ] Rename packages, i.e. remove `@paloaltonetworks/` scope and rename folders and `package.json` "name"
- [ ] Rename repository (GitHub will auto-redirect old to new)
- [ ] Final scrub/cleanup
- [ ] Publish new packages to npmjs
